# Generated by Django 5.2.6 on 2025-10-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Empresa')),
                ('persona_contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_estandar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Estándar')),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['nombre_servicio'],
            },
        ),
    ]
