# Generated by Django 5.2.6 on 2025-11-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_empresa',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='costo_estandar',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo estándar'),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='nombre_servicio',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del servicio'),
        ),
    ]
