# Generated by Django 5.2.6 on 2025-11-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Computadora de escritorio', 'Computadora de escritorio'), ('Impresora', 'Impresora'), ('Proyector', 'Proyector'), ('Componente de computadora', 'Componente de computadora')], help_text='Ej. Laptop, Impresora, Proyector', max_length=100, verbose_name='Tipo de equipo'),
        ),
    ]
