# Generated by Django 5.2.6 on 2025-12-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0002_alter_cliente_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='contrasena_equipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña del Equipo (Cifrada)'),
        ),
    ]
