# Generated by Django 5.2.6 on 2026-01-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clientes', '0003_equipo_contrasena_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='contrasena_equipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña (Encriptada)'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie'),
        ),
    ]
