# Generated by Django 5.2.6 on 2025-10-28 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('gestion_clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_falla', models.TextField(verbose_name='Descripción de la Falla')),
                ('contrasena_equipo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña del Equipo (Encriptada)')),
                ('estado', models.CharField(choices=[('Nueva', 'Nueva'), ('En Diagnóstico', 'En Diagnóstico'), ('Esperando Autorización', 'Esperando Autorización'), ('Esperando Refacción', 'Esperando Refacción'), ('En Reparación', 'En Reparación'), ('Finalizada por Técnico', 'Finalizada por Técnico'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], default='Nueva', max_length=50)),
                ('prioridad', models.CharField(choices=[('Baja', 'Baja'), ('Normal', 'Normal'), ('Alta', 'Alta')], default='Normal', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('asistente_receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Asistente que Recibió')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='gestion_clientes.cliente')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='gestion_clientes.equipo')),
                ('servicios', models.ManyToManyField(blank=True, related_name='ordenes', to='catalogo.tiposervicio', verbose_name='Servicios Aplicados')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.TextField()),
                ('costo_refacciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de Enviar'), ('Enviada', 'Enviada al Cliente'), ('Autorizada', 'Autorizada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=50)),
                ('fuente_refaccion', models.CharField(blank=True, choices=[('Stock Interno', 'Stock Interno'), ('Pedido a Proveedor', 'Pedido a Proveedor')], max_length=50, null=True, verbose_name='Fuente de la Refacción')),
                ('tipo_cotizacion', models.CharField(choices=[('Refacción Interna', 'Refacción Interna (Recepción)'), ('Proyecto Venta', 'Proyecto/Venta (Ventas)')], default='Refacción Interna', max_length=50, verbose_name='Tipo de Cotización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas/Observaciones')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='catalogo.proveedor')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='gestion_ordenes.ordenservicio')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('descripcion', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_bitacora', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='gestion_ordenes.ordenservicio')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Bitácora de Órdenes',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de Referencia')),
                ('fecha_transferencia', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Transferencia')),
                ('notas', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='gestion_ordenes.ordenservicio')),
                ('usuario_autoriza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Autoriza')),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
            options={
                'verbose_name': 'Transferencia de Almacén',
                'verbose_name_plural': 'Transferencias de Almacén',
                'ordering': ['-fecha_transferencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemTransferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_item', models.CharField(max_length=255, verbose_name='Descripción del Ítem')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion_ordenes.transferencia')),
            ],
            options={
                'verbose_name': 'Ítem Transferido',
                'verbose_name_plural': 'Ítems Transferidos',
            },
        ),
    ]
