# Generated by Django 5.2.6 on 2025-11-16 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_proveedor_nombre_empresa_and_more'),
        ('gestion_ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fuente_refaccion',
            field=models.CharField(blank=True, choices=[('Stock interno', 'Stock interno'), ('Pedido a proveedor', 'Pedido a proveedor')], max_length=50, null=True, verbose_name='Fuente de la refacción'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_cotizacion',
            field=models.CharField(choices=[('Cotización interna', 'Cotización interna (Recepción)'), ('Cotización externa', 'Cotización externa (Ventas)')], default='Cotización interna', max_length=50, verbose_name='Tipo de cotización'),
        ),
        migrations.AlterField(
            model_name='itemtransferido',
            name='descripcion_item',
            field=models.CharField(max_length=255, verbose_name='Descripción del ítem'),
        ),
        migrations.AlterField(
            model_name='itemtransferido',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='asistente_receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Asistente que recibió'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='contrasena_equipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña del equipo (Encriptada)'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='descripcion_falla',
            field=models.TextField(verbose_name='Descripción de la falla'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='estado',
            field=models.CharField(choices=[('Nueva', 'Nueva'), ('En diagnóstico', 'En diagnóstico'), ('Esperando autorización', 'Esperando autorización'), ('Esperando refacción', 'Esperando refacción'), ('En reparación', 'En reparación'), ('Finalizada por Técnico', 'Finalizada por Técnico'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], default='Nueva', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='ordenes', to='catalogo.tiposervicio', verbose_name='Servicios aplicados'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='documento_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de referencia'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='fecha_transferencia',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de transferencia'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='usuario_autoriza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que autoriza'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='usuario_solicitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario solicitante'),
        ),
    ]
