# Generated by Django 5.2.6 on 2026-01-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ordenes', '0002_alter_cotizacion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraorden',
            name='contenido_original',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido original (Pre-edición)'),
        ),
        migrations.AddField(
            model_name='bitacoraorden',
            name='editado',
            field=models.BooleanField(default=False, verbose_name='Editado'),
        ),
        migrations.AddField(
            model_name='bitacoraorden',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de última edición'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fuente_refaccion',
            field=models.CharField(blank=True, choices=[('Stock interno', 'Stock interno (General o De Servicio)'), ('Pedido a proveedor', 'Pedido a proveedor')], max_length=50, null=True, verbose_name='Fuente de la refacción'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_cotizacion',
            field=models.CharField(choices=[('Cotización interna', 'Cotización interna'), ('Cotización externa', 'Cotización externa (Ventas)')], default='Cotización interna', max_length=50, verbose_name='Tipo de cotización'),
        ),
    ]
