# Generated by Django 5.2.6 on 2026-01-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ordenes', '0003_bitacoraorden_contenido_original_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraorden',
            name='contenido_original',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido original (Pre-ediciones)'),
        ),
    ]
